Instalar librerías

In [1]:
%pip install pandas numpy

Collecting pandas
  Using cached pandas-3.0.2-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting numpy
  Downloading numpy-2.4.4-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\bootcamp_datascience\ejercicios\proyecto_1\myenv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Downloading tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in d:\bootcamp_datascience\ejercicios\proyecto_1\myenv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.2-cp312-cp312-win_amd64.whl (9.7 MB)
Downloading numpy-2.4.4-cp312-cp312-win_amd64.whl (12.3 MB)
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.1/12.3 MB 2.1 MB/s eta 0:00:06
   --- ------------------------------------ 1.0/12.3 MB 7.5 MB/s eta 0:00:02
   ---- ----------------------------------- 1.4/12.3 MB 8.6 MB/s eta 0:00:02
   ------- -------------------------------- 2.2/12.3 MB 10.0 MB/s eta 0:00:02
   ---------- ----------------------------- 3.1/12.3 MB 12.5 MB/s eta 0:00:01
   ------------ --------------------------- 3.8/12.3 MB 12.7 MB/s eta 0:00:01
   -------------- ------------------------- 4.5/12.3 MB 13.0 MB/s eta 0:00:01
   ----------------- ---------------------- 5.3/12.3 MB 13.5 MB/s eta 0:00:01
   -------------------- ------------------- 6.2/12.3 MB 14.1 MB/s eta 0:00:01
   ---------------------- ----------------- 7.0/12.3 MB 14.5 MB/s eta 0:00:01
   ------------------------- -------------- 8.0/12.3 MB 15.0 MB/s eta 0:00:01
   ----------------------------- ---------- 8.9/12.3 MB 15.5 MB/s eta 0:00:01
   ------------------------------- -------- 9.8/12.3 MB 15.6 MB/s eta 0:00:01
   ---------------------------------- ----- 10.7/12.3 MB 17.7 MB/s eta 0:00:01
   ------------------------------------- -- 11.5/12.3 MB 17.7 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.3 MB 18.7 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.3 MB 18.7 MB/s eta 0:00:01
   ---------------------------------------  12.3/12.3 MB 18.7 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 15.2 MB/s eta 0:00:00
Downloading tzdata-2026.2-py2.py3-none-any.whl (349 kB)
   ---------------------------------------- 0.0/349.3 kB ? eta -:--:--
   --------------------------------------- 349.3/349.3 kB 10.9 MB/s eta 0:00:00
Installing collected packages: tzdata, numpy, pandas
Successfully installed numpy-2.4.4 pandas-3.0.2 tzdata-2026.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Carga de Datos

In [13]:
import pandas as pd
import numpy as np

#Cargar el archivo en un Data Frame de Pandas
df = pd.read_csv('../data/retail_sales_dataset.csv')

#Mostrar las primeras 10 filas del Data Frame
df.head(10)

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
5,6,2023-04-25,CUST006,Female,45,Beauty,1,30,30
6,7,2023-03-13,CUST007,Male,46,Clothing,2,25,50
7,8,2023-02-22,CUST008,Male,30,Electronics,4,25,100
8,9,2023-12-13,CUST009,Male,63,Electronics,2,300,600
9,10,2023-10-07,CUST010,Female,52,Clothing,4,50,200

Exploración inicial de los Datos

In [14]:
# Mostramos las últimas 5 filas del Data Frame
print("=" * 50)
print("Últimas 5 filas: ")
display(df.tail(5))

# Mostramos información general del Data Frame
print("=" * 50)
print("Información general del Data Frame: ")
display(df.info())

# Generamos estadísticas descriptivas del Data Frame
print("=" * 50)
print("Estadísticas descriptivas del Data Frame: ")
display(df.describe())

# Mostramos el número de filas y columnas del Data Frame
print("=" * 50)
print("Número de filas y columnas del Data Frame: ")
display(df.shape)

# Mostramos si hay duplicados en el Data Frame
print("=" * 50)
print("Duplicados en el Data Frame: ")
display(df.duplicated().sum())

# Mostramos los valores nulos en cada columna del Data Frame
print("=" * 50)
print("Valores nulos en cada columna del Data Frame: ")
display(df.isnull().sum())

==================================================
Últimas 5 filas:

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

==================================================
Información general del Data Frame:
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   str
 2   Customer ID       1000 non-null   str
 3   Gender            1000 non-null   str
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   str
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), str(4)
memory usage: 70.4 KB

None

==================================================
Estadísticas descriptivas del Data Frame:

       Transaction ID         Age     Quantity  Price per Unit  Total Amount
count     1000.000000  1000.00000  1000.000000     1000.000000   1000.000000
mean       500.500000    41.39200     2.514000      179.890000    456.000000
std        288.819436    13.68143     1.132734      189.681356    559.997632
min          1.000000    18.00000     1.000000       25.000000     25.000000
25%        250.750000    29.00000     1.000000       30.000000     60.000000
50%        500.500000    42.00000     3.000000       50.000000    135.000000
75%        750.250000    53.00000     4.000000      300.000000    900.000000
max       1000.000000    64.00000     4.000000      500.000000   2000.000000

==================================================
Número de filas y columnas del Data Frame:

(1000, 9)

==================================================
Duplicados en el Data Frame:

np.int64(0)

==================================================
Valores nulos en cada columna del Data Frame:

Transaction ID      0
Date                0
Customer ID         0
Gender              0
Age                 0
Product Category    0
Quantity            0
Price per Unit      0
Total Amount        0
dtype: int64

Inspección de los Datos

In [17]:
# Tipos de datos de cada columna del Data Frame
print("=" * 50)
print("Tipos de datos de cada columna del Data Frame: ")
display(df.dtypes)

# Valores únicos de la columna Producto
# Al no existir la columna 'Producto' en el Data Frame, se asume que se refiere a 'Product Category'
print("=" * 50)
print("Valores únicos de la columna 'Product Category': ")
display(df.value_counts('Product Category'))

# Muestra todos los valores únicos en la columna Tienda 
# Al no existir la columna 'Tienda' en el Data Frame, se decide inspeccionar 'Price per Unit'
print("=" * 50)
print("Valores únicos de la columna 'Price per Unit': ")
display(df['Price per Unit'].unique())

==================================================
Tipos de datos de cada columna del Data Frame:

Transaction ID      int64
Date                  str
Customer ID           str
Gender                str
Age                 int64
Product Category      str
Quantity            int64
Price per Unit      int64
Total Amount        int64
dtype: object

==================================================
Valores únicos de la columna 'Product Category':

Product Category
Clothing       351
Electronics    342
Beauty         307
Name: count, dtype: int64

==================================================
Valores únicos de la columna 'Price per Unit':

array([ 50, 500,  30,  25, 300])

Filtrado de Datos

In [18]:
# Filas donde las ventas (Ventas) sean mayores a 50
# Al no existir la columna 'Ventas' en el Data Frame, se decide filtrar por 'Total Amount'
print("=" * 50)
print("Filas donde las ventas son mayores a 50: ")
display(df[df['Total Amount'] > 50])

# Filas donde las ventas sean mayores a 500
# Como la mayoría las ventas están sobre 50, se decide mostrar también las filas donde las ventas sean mayores a 500 
print("=" * 50)
print("Filas donde las ventas son mayores a 500: ")
display(df[df['Total Amount'] > 500])

# Filas donde el precio (Precio) sea menor a 0.5
# Al no existir la columna 'Precio' en el Data Frame, se decide filtrar por 'Price per Unit'
print("=" * 50)
print("Filas donde el precio es menor a 0.5: ")
display(df[df['Price per Unit'] < 0.5])

# Filas donde el precio sea menor a 50
# Como no hay precios menores a 0.5, se decide mostrar también las filas donde el precio sea menor a 50
print("=" * 50)
print("Filas donde el precio es menor a 50:")
display(df[df['Price per Unit'] < 50])

# Filas donde el producto sea Manzanas y las ventas sean mayores a 30.
# Al no existir el producto 'Manzanas' en el Data Frame, se decide utilizar la categoría 'Electronics'
print("=" * 50)
print("Filas donde el producto es 'Electronics' y las ventas son mayores a 30: ")
display(df.query("`Product Category` == 'Electronics' and `Total Amount` > 30"))

==================================================
Filas donde las ventas son mayores a 50:

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
7,8,2023-02-22,CUST008,Male,30,Electronics,4,25,100
...,...,...,...,...,...,...,...,...,...
993,994,2023-12-18,CUST994,Female,51,Beauty,2,500,1000
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

==================================================
Filas donde las ventas son mayores a 500:

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
8,9,2023-12-13,CUST009,Male,63,Electronics,2,300,600
12,13,2023-08-05,CUST013,Male,22,Electronics,3,500,1500
14,15,2023-01-16,CUST015,Female,42,Electronics,4,500,2000
15,16,2023-02-17,CUST016,Male,19,Clothing,3,500,1500
...,...,...,...,...,...,...,...,...,...
975,976,2023-10-10,CUST976,Female,48,Beauty,2,300,600
985,986,2023-01-17,CUST986,Female,49,Clothing,2,500,1000
986,987,2023-04-29,CUST987,Female,30,Clothing,3,300,900
989,990,2023-05-25,CUST990,Female,58,Beauty,2,500,1000
993,994,2023-12-18,CUST994,Female,51,Beauty,2,500,1000

==================================================
Filas donde el precio es menor a 0.5:

Empty DataFrame
Columns: [Transaction ID, Date, Customer ID, Gender, Age, Product Category, Quantity, Price per Unit, Total Amount]
Index: []

==================================================
Filas donde el precio es menor a 50:

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
5,6,2023-04-25,CUST006,Female,45,Beauty,1,30,30
6,7,2023-03-13,CUST007,Male,46,Clothing,2,25,50
7,8,2023-02-22,CUST008,Male,30,Electronics,4,25,100
11,12,2023-10-30,CUST012,Male,35,Beauty,3,25,75
...,...,...,...,...,...,...,...,...,...
991,992,2023-08-21,CUST992,Female,57,Electronics,2,30,60
994,995,2023-04-30,CUST995,Female,41,Clothing,1,30,30
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

==================================================
Filas donde el producto es 'Electronics' y las ventas son mayores a 30:

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
7,8,2023-02-22,CUST008,Male,30,Electronics,4,25,100
8,9,2023-12-13,CUST009,Male,63,Electronics,2,300,600
12,13,2023-08-05,CUST013,Male,22,Electronics,3,500,1500
14,15,2023-01-16,CUST015,Female,42,Electronics,4,500,2000
17,18,2023-04-30,CUST018,Female,47,Electronics,2,25,50
...,...,...,...,...,...,...,...,...,...
984,985,2023-05-30,CUST985,Female,19,Electronics,2,25,50
991,992,2023-08-21,CUST992,Female,57,Electronics,2,30,60
992,993,2023-02-06,CUST993,Female,48,Electronics,3,50,150
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

Slicing de Datos

In [19]:
# Mostramos sólo las columnas de Producto y Ventas
# Al no existir la columna 'Producto' en el Data Frame, se asume que se refiere a 'Product Category'
# Al no existir la columna 'Ventas' en el Data Frame, se asume que se refiere a 'Total Amount'
print("=" * 50)
print("Columnas Product Category y Total Amount:")
display(df[['Product Category', 'Total Amount']])

# Filas de las 5 a 10 y las columnas Producto y Tienda.
# Al no existir la columna 'Producto' en el Data Frame, se asume que se refiere a 'Product Category'
# Al no existir la columna 'Tienda' en el Data Frame, se decide filtrar por 'Price per Unit'
print("=" * 50)
print("Filas 5 a 10 de las columnas de Product Category y Price per Unit:")
display(df[['Product Category', 'Price per Unit']].iloc[5:11])

# Primeras 5 filas y primeras 3 columnas del Data Frame
print("=" * 50)
print("Primeras 5 filas y primeras 3 columnas del Data Frame:")
display(df.iloc[0:5, 0:3])

==================================================
Columnas Product Category y Total Amount:

    Product Category  Total Amount
0             Beauty           150
1           Clothing          1000
2        Electronics            30
3           Clothing           500
4             Beauty           100
..               ...           ...
995         Clothing            50
996           Beauty            90
997           Beauty           100
998      Electronics           150
999      Electronics           120

[1000 rows x 2 columns]

==================================================
Filas 5 a 10 de las columnas de Product Category y Price per Unit:

   Product Category  Price per Unit
5            Beauty              30
6          Clothing              25
7       Electronics              25
8       Electronics             300
9          Clothing              50
10         Clothing              50

==================================================
Primeras 5 filas y primeras 3 columnas del Data Frame:

   Transaction ID        Date Customer ID
0               1  2023-11-24     CUST001
1               2  2023-02-27     CUST002
2               3  2023-01-13     CUST003
3               4  2023-05-21     CUST004
4               5  2023-05-06     CUST005