Carga de Datos

In [21]:
import pandas as pd
import numpy as np

#Cargar el archivo en un Data Frame de Pandas
df = pd.read_csv('../data/retail_sales_dataset.csv')

#Mostrar las primeras 10 filas del Data Frame
df.head(10)

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
5,6,2023-04-25,CUST006,Female,45,Beauty,1,30,30
6,7,2023-03-13,CUST007,Male,46,Clothing,2,25,50
7,8,2023-02-22,CUST008,Male,30,Electronics,4,25,100
8,9,2023-12-13,CUST009,Male,63,Electronics,2,300,600
9,10,2023-10-07,CUST010,Female,52,Clothing,4,50,200

Exploración inicial

In [22]:
# Mostramos las últimas 5 filas del Data Frame
print("=" * 50)
print("Últimas 5 filas: ")
display(df.tail(5))

# Mostramos información general del Data Frame
print("=" * 50)
print("Información general del Data Frame: ")
display(df.info())

# Generamos estadísticas descriptivas del Data Frame
print("=" * 50)
print("Estadísticas descriptivas del Data Frame: ")
display(df.describe())

# Mostramos el número de filas y columnas del Data Frame
print("=" * 50)
print("Número de filas y columnas del Data Frame: ")
display(df.shape)

# Mostramos si hay duplicados en el Data Frame
print("=" * 50)
print("Duplicados en el Data Frame: ")
display(df.duplicated().sum())

# Mostramos los valores nulos en cada columna del Data Frame
print("=" * 50)
print("Valores nulos en cada columna del Data Frame: ")
display(df.isnull().sum())

==================================================
Últimas 5 filas:

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

==================================================
Información general del Data Frame:
<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   str
 2   Customer ID       1000 non-null   str
 3   Gender            1000 non-null   str
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   str
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: int64(5), str(4)
memory usage: 70.4 KB

None

==================================================
Estadísticas descriptivas del Data Frame:

       Transaction ID         Age     Quantity  Price per Unit  Total Amount
count     1000.000000  1000.00000  1000.000000     1000.000000   1000.000000
mean       500.500000    41.39200     2.514000      179.890000    456.000000
std        288.819436    13.68143     1.132734      189.681356    559.997632
min          1.000000    18.00000     1.000000       25.000000     25.000000
25%        250.750000    29.00000     1.000000       30.000000     60.000000
50%        500.500000    42.00000     3.000000       50.000000    135.000000
75%        750.250000    53.00000     4.000000      300.000000    900.000000
max       1000.000000    64.00000     4.000000      500.000000   2000.000000

==================================================
Número de filas y columnas del Data Frame:

(1000, 9)

==================================================
Duplicados en el Data Frame:

np.int64(0)

==================================================
Valores nulos en cada columna del Data Frame:

Transaction ID      0
Date                0
Customer ID         0
Gender              0
Age                 0
Product Category    0
Quantity            0
Price per Unit      0
Total Amount        0
dtype: int64

Transformación de Datos

In [23]:
# Hacemos una copia del Data Frame original para trabajar con ella
df_retail = df.copy()

# Creamos la columna 'Customer_Segment' basada en la edad de los clientes
# Definimos los cortes de edad y sus etiquetas
bins_edad = [0, 25, 40, 60, 100]
etiquetas_edad = ['Gen Z', 'Millennial', 'Adulto', 'Senior']

df_retail['Customer_Segment'] = pd.cut(df_retail['Age'], bins=bins_edad, labels=etiquetas_edad)
# Mostramos las primeras 5 filas del Data Frame después de crear la columna 'Customer_Segment'
print("=" * 50)
print("Primeras 5 filas después de crear 'Customer_Segment': ")
display(df_retail.head(5))

==================================================
Primeras 5 filas después de crear 'Customer_Segment':

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount,Customer_Segment
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150,Millennial
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000,Millennial
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30,Adulto
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500,Millennial
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100,Millennial

In [24]:

# Convertimos la columna 'Date' a formato datetime para normalizarla
df_retail['Date'] = pd.to_datetime(df_retail['Date'], format='%Y-%m-%d')

# Mostramos las primeras 5 filas del Data Frame después de la conversión
print("=" * 50)
print("Primeras 5 filas después de convertir 'Date' a datetime: ")
display(df_retail.head(5))

==================================================
Primeras 5 filas después de convertir 'Date' a datetime:

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount,Customer_Segment
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150,Millennial
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000,Millennial
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30,Adulto
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500,Millennial
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100,Millennial

In [10]:
# Crea una columna que clasifique las ventas en categorías significativas (‘Alta’, ‘Media’, ‘Baja’).
# Definimos los cortes de ventas y sus etiquetas
bins_ventas = [0, 100, 500, np.inf]
etiquetas_ventas = ['Baja', 'Media', 'Alta']
df_retail['Sales_Category'] = pd.cut(df_retail['Total Amount'], bins=bins_ventas, labels=etiquetas_ventas)
# Mostramos las primeras 5 filas del Data Frame después de crear la columna 'Sales_Category'
print("=" * 50)
print("Primeras 5 filas después de crear 'Sales_Category': ")
display(df_retail.head(5))

==================================================
Primeras 5 filas después de crear 'Sales_Category':

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount,Customer_Segment,Sales_Category
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150,Millennial,Media
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000,Millennial,Alta
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30,Adulto,Baja
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500,Millennial,Media
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100,Millennial,Baja

Agrupación y Agregación

In [25]:
# Agrupamos por Categoría de Producto y Género
# Calculamos la suma, media y conteo de 'Total Amount' y la suma de 'Quantity' para cada grupo
producto_genero = df_retail.groupby(['Product Category', 'Gender']).agg({'Total Amount': ['sum', 'mean', 'count'], 'Quantity': sum})

# Mostramos el resultado del agrupamiento
print("=" * 50)
print("Resultado del agrupamiento por Categoría de Producto y Género:")
display(producto_genero)

==================================================
Resultado del agrupamiento por Categoría de Producto y Género:

                        Total Amount                   Quantity
                                 sum        mean count      sum
Product Category Gender
Beauty           Female        74830  450.783133   166      418
                 Male          68685  487.127660   141      353
Clothing         Female        81275  467.097701   174      441
                 Male          74305  419.802260   177      453
Electronics      Female        76735  451.382353   170      439
                 Male          80170  466.104651   172      410

In [26]:
# Hacemos una agregación múltiple para obtener la suma, media y conteo, venta máxima y mínima, dispersión y varianza por Categoría de Producto
estadisticas_ventas = df_retail.groupby('Product Category')['Total Amount'].agg(['sum', 'mean', 'count', 'min', 'max', 'std', 'var'])
# Mostramos el resultado de la agregación múltiple
print("=" * 50)
print("Estadísticas de ventas por categoría de producto:")
display(estadisticas_ventas)

==================================================
Estadísticas de ventas por categoría de producto:

,sum,mean,count,min,max,std,var
Product Category,,,,,,,
Beauty,143515,467.475570,307,25,2000,563.612788,317659.374401
Clothing,155580,443.247863,351,25,2000,550.695917,303265.992674
Electronics,156905,458.786550,342,25,2000,567.540150,322101.822341

Análisis Personalizado con apply

In [27]:
# Hacemos una función para clasificar el tipo de boleta según volumen y precio
def clasificar_boleta(fila):
    if fila['Quantity'] > 3 and fila['Price per Unit'] > 200:
        return 'Volumen Alto'
    elif fila['Quantity'] <= 2 and fila['Price per Unit'] > 400:
        return 'Compra Única Alta'
    elif fila['Total Amount'] < 100:
        return 'Low Cost'
    else:
        return 'Venta Estándar'

# Aplicamos la función fila por fila
df_retail['Ticket_Type'] = df_retail.apply(clasificar_boleta, axis=1)

print("Distribución de tipos de boleta:")
print(df_retail['Ticket_Type'].value_counts())
display(df_retail.head(5))

Distribución de tipos de boleta:
Ticket_Type
Venta Estándar       448
Low Cost             349
Volumen Alto         103
Compra Única Alta    100
Name: count, dtype: int64

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount,Customer_Segment,Ticket_Type
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150,Millennial,Venta Estándar
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000,Millennial,Compra Única Alta
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30,Adulto,Low Cost
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500,Millennial,Compra Única Alta
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100,Millennial,Venta Estándar

In [32]:
# Calculamos el porcentaje de desviación de cada venta respecto a la media de su categoría de producto
# Primero calculamos la media de 'Total Amount' por categoría de producto
def calcular_desviación(fila):
    media_categoria = df_retail[df_retail['Product Category'] == fila['Product Category']]['Total Amount'].mean()
    desviacion = (fila['Total Amount'] - media_categoria) / media_categoria * 100
    return desviacion

# Aplicamos la función fila por fila
df_retail['Desviacion_Porcentual'] = df_retail.apply(calcular_desviación, axis=1)

# Mostramos las ventas que más se alejaron de la media de su categoría de producto
print("=" * 50)
print("Ventas que más se alejaron de la media de su categoría:")
display(df_retail[['Product Category', 'Total Amount', 'Desviacion_Porcentual']].sort_values(by='Desviacion_Porcentual', ascending=False).head(10))

==================================================
Ventas que más se alejaron de la media de su categoría:

    Product Category  Total Amount  Desviacion_Porcentual
419         Clothing          2000             351.214809
475         Clothing          2000             351.214809
252         Clothing          2000             351.214809
268         Clothing          2000             351.214809
560         Clothing          2000             351.214809
571         Clothing          2000             351.214809
546         Clothing          2000             351.214809
486         Clothing          2000             351.214809
625         Clothing          2000             351.214809
594         Clothing          2000             351.214809